#!/bin/bash

dcu() {
  docker-compose up --build
}

db() {
  docker build -t "${1}" .
}

drmi() {
  local imageIds
  if [ $# -gt 1 ] && [ "$1" = "--pattern" ]; then
    shift
    imageIds=( $(docker images | grep $1 | awk '{print $3}') )
  elif [ $# -eq 0 ]; then
    imageIds=( $(docker images -q ) )
  else
    imageIds=( $(echo $@) )
  fi

  if (( ${#imageIds[@]} != 0 )); then
    docker rmi -f ${imageIds}
  fi
}
drm() {
  local containerIds
  if [ $# -gt 1 ] && [ "$1" = "--pattern" ]; then
    containerIds="$(docker ps -a | grep $2 | awk '{print $1}')"
  elif [ $# -eq 0 ]; then
    containerIds="$(docker ps -a -q)"
  else
    containerIds="$(echo "$@" | tr ' ' '\n')"
  fi

  containerIds=( $(echo $containerIds | tr '\n' ' ') )
  if (( ${#containerIds[@]} != 0 )); then
    docker rm -f ${containerIds}
  fi
}

dr() {
  docker run -it --rm ${@}
}

dli() {
  docker images
}

dla() {
  docker ps -a
}
