set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'kongo2002/fsharp-vim'

call vundle#end()
filetype plugin indent on


set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set number        " display line numbers on the left

set showcmd       " show command in bottom bar

set wildmenu      " visual autocomplete for command menu
set lazyredraw    " only redraw when we need to
set showmatch     " highlight matching [{()}]

set incsearch     " search while characters are entered
set hlsearch      " highlight matches

nnoremap ,<space> :nohlsearch<CR>

color ron
syntax enable


